version: '3'
services:
#  web:
#      build:
#        context: .
#        dockerfile: ./web/nginx/Dockerfile
#      ports:
#          - "80:80"
#          - "443:443"
#      volumes:
#        - ./src/html:/var/www/html
#      depends_on:
#          - php
#  php:
#      build:
#        context: .
#        dockerfile: ./php/php-fpm/Dockerfile
#      volumes:
#        - ./src/html:/var/www/html
#  db:
#      buld:
#        context: .
#      volumes: ./db/data:/var/lib/mysql
  jenkins:
    container_name: jenkins
    image: jenkins:latest
    ports:
      - 18080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
