version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ./web/nginx/Dockerfile
      ports:
          - "80:80"
      depends_on:
          - php
  php:
      build:
        context: .
        dockerfile: ./php/php-fpm/Dockerfile
