version: '3'
services:
#  web:
#      build:
#        context: .
#        dockerfile: ./web/nginx/Dockerfile
#      ports:
#          - "80:80"
#          - "443:443"
#      volumes:
#        - ./src/html:/var/www/html
#      depends_on:
#          - php
#  php:
#      build:
#        context: .
#        dockerfile: ./php/php-fpm/Dockerfile
#      volumes:
#        - ./src/html:/var/www/html
#  db:
#      buld:
#        context: .
#      volumes: ./db/data:/var/lib/mysql
  jenkins:
    container_name: jenkins
    image: jenkins:latest
    ports:
      - 18080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
  gitbucket:
    container_name: gitbucket
    image: gitbucket/gitbucket
    ports:
      - 8080:8080
    volumes:
       - ~/gitbucket_home/:/gitbucket/
#    environment:
#       - VIRTUAL_HOST=gitbucket.chalkfinger.com
#       - VIRTUAL_PORT=8080
#       - CERT_NAME=mydomain
#       - HTTPS_METHOD=noredirect
    restart: always
