version: '3'
services:
  slapd:
    build: .
    tty: true
    container_name: openldap
    environment:
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_DOMAIN=lazyarea.com
      - LDAP_ORGANISATION=Lazyarea Inc.
    networks:
      - ldap_nw
    ports:
      - "389:389"
      - "689:689"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - './srv/ldap:/var/lib/ldap'
networks:
  ldap_nw:
    external: true
